SHOW PARAMETER audit_trail;


alter session set container=cdb$root;
alter session set container = PDBQLDLNB;
ALTER SYSTEM SET audit_trail=db, extended SCOPE=SPFILE;


--kích ho?t audit 
alter session set container=cdb$root;
ALTER SYSTEM SET audit_trail=db SCOPE=SPFILE;
alter session set container = PDBQLDLNB;

CREATE OR REPLACE PROCEDURE SP_KICHHOATAUDIT
    (TABLE_NAME VARCHAR2,
   
    ISSUCCESS VARCHAR2,
    NOTSUCCESS VARCHAR2,
    ACTION VARCHAR2
    )
AS
    STRSQL VARCHAR(2000);
BEGIN
    STRSQL := 'AUDIT ' || ACTION || ' ON ADMIN.' ||TABLE_NAME ;
    
     STRSQL := STRSQL || ' BY ACCESS';
    IF (ISSUCCESS = 'TRUE') THEN 
        STRSQL := STRSQL || ' WHENEVER SUCCESSFUL';
    ELSIF (NOTSUCCESS = 'TRUE') THEN
        STRSQL := STRSQL || ' WHENEVER NOT SUCCESSFUL';
    END IF;
   
    DBMS_OUTPUT.PUT_LINE(STRSQL);
   EXECUTE IMMEDIATE (STRSQL);
END;
/
SET SERVEROUTPUT ON;
EXEC SP_KICHHOATAUDIT('DANGKY', 'TRUE', 'FALSE', 'SELECT');

NOAUDIT SELECT ON ADMIN.NHANSU WHENEVER SUCCESSFUL

/
AUDIT SELECT ON ADMIN.DANGKY BY test123 BY ACCESS WHENEVER SUCCESSFUL ;
/
AUDIT SELECT on admin.dangky by access
    BY test123;
SELECT  * FROM DBA_TAB_PRIVS;

SELECT * FROM all_tables where OWNER = 'ADMIN';


SELECT * FROM DBA_STMT_AUDIT_OPTS;

SELECT * FROM DBA_OBJ_AUDIT_OPTS WHERE OWNER ='ADMIN';

SELECT *
FROM DBA_AUDIT_TRAIL;


ALTER PLUGGABLE DATABASE PDBQLDLNB OPEN;

SELECT * 
FROM DBA_AUDIT_TRAIL ;

SHOW PARAMETER AUDIT_TRAIL;

SELECT COUNT(*) AS num_sys_accounts
FROM DBA_ROLE_PRIVS
WHERE GRANTED_ROLE = 'SYSDBA' OR GRANTED_ROLE = 'SYSOPER';

SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTED_ROLE LIKE '%DBA%';