CREATE TABLE NHANSU
(
   MANV CHAR(6),
   HOTEN NVARCHAR2(50),
   PHAI NCHAR(3),
   NGSINH DATE,
   PHUCAP FLOAT,
   DT CHAR(10),
   VAITRO NVARCHAR2(20),
   MADV CHAR(5),
    
    PRIMARY KEY(MANV)
);

CREATE TABLE SINHVIEN
(
    MASV CHAR(8),
    HOTEN NVARCHAR2(50),
    PHAI NCHAR(3),
    NGSINH DATE,
    DCHI NVARCHAR2(100),
    DT CHAR(10),
    MACT CHAR(4),
    MANGANH CHAR(8),
    SOTCTL NUMBER,
    DTBTL FLOAT,
    
    PRIMARY KEY (MASV)
);

CREATE TABLE DONVI 
(
    MADV CHAR(7),
    TENDV NVARCHAR2(30),
    TRGDV CHAR(6),
    
    PRIMARY KEY (MADV)
);

ALTER TABLE DONVI
ADD
    CONSTRAINT FK_DV_NS
    FOREIGN KEY (TRGDV)
    REFERENCES NHANSU;
    
CREATE TABLE HOCPHAN
(
    MAHP CHAR(8),
    TENHP NVARCHAR2(30),
    SOTC NUMBER,
    STLT NUMBER,
    STTH NUMBER,
    SOSVTD NUMBER,
    MADV CHAR(7),
    
    PRIMARY KEY (MAHP)
);
ALTER TABLE HOCPHAN
ADD
    CONSTRAINT FK_HP_DV
    FOREIGN KEY (MADV)
    REFERENCES DONVI;
    
CREATE TABLE KHMO
(
    MAHP CHAR(8),
    HK NUMBER,
    NAM NUMBER,
    MACT CHAR(4),
    
    PRIMARY KEY (MAHP, HK, NAM, MACT)
);

ALTER TABLE KHMO
ADD
    CONSTRAINT FK_KH_HP
    FOREIGN KEY (MAHP)
    REFERENCES HOCPHAN;

CREATE TABLE PHANCONG
(
    MAGV CHAR(6),
    MAHP CHAR(8),
    HK NUMBER,
    NAM NUMBER,
    MACT CHAR(4),
    
    PRIMARY KEY (MAGV, MAHP, HK, NAM, MACT)
);

ALTER TABLE PHANCONG
ADD
    CONSTRAINT FK_PC_NS
    FOREIGN KEY (MAGV)
    REFERENCES NHANSU;

ALTER TABLE PHANCONG
ADD
    CONSTRAINT FK_PC_KH
    FOREIGN KEY (MAHP, HK, NAM, MACT)
    REFERENCES KHMO;

CREATE TABLE DANGKY
(
    MASV CHAR(8),
    MAGV CHAR(6),
    MAHP CHAR(8),
    HK NUMBER,
    NAM NUMBER,
    MACT CHAR(4),
    DIEMTH FLOAT,
    DIEMQT FLOAT,
    DIEMCK FLOAT,
    DIEMTK FLOAT,
    
    PRIMARY KEY (MASV,MAGV, MAHP, HK, NAM, MACT)
);

ALTER TABLE DANGKY
ADD 
    CONSTRAINT FK_DK_PC
    FOREIGN KEY (MAGV, MAHP, HK, NAM, MACT)
    REFERENCES PHANCONG;

ALTER TABLE DANGKY
ADD
    CONSTRAINT FK_DK_SV
    FOREIGN KEY (MASV)
    REFERENCES SINHVIEN;
    
--DROP TABLE DANGKY;
--DROP TABLE PHANCONG;
--DROP TABLE KHMO;
--DROP TABLE HOCPHAN;
--DROP TABLE DONVI;
--DROP TABLE SINHVIEN;
--DROP TABLE NHANSU;
--
--    

