

-- PAGE NHANSU
-- LAY THONG TIN NHAN SU
ALTER SESSION SET CURRENT_SCHEMA = ADMIN;
CREATE OR REPLACE PROCEDURE SP_GetEmpInfo(
    empInfo OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN empInfo FOR
    SELECT NHANSU.*, ADMIN.DONVI.TENDV AS TEN_DONVI
    FROM ADMIN.NHANSU
    LEFT JOIN ADMIN.DONVI ON ADMIN.NHANSU.MADV = ADMIN.DONVI.MADV;
END SP_GetEmpInfo;
/

-- CAP NHAT SDT
CREATE OR REPLACE PROCEDURE SP_UpdateEmpPhoneNumber(
    newPhone_param IN CHAR
)
AS
BEGIN
    UPDATE ADMIN.NHANSU
    SET DT = newPhone_param;  
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_UpdateEmpPhoneNumber;
/
EXEC SP_GrantExcuteToUser('SP_UpdateEmpPhoneNumber');
/


SELECT * 
FROM ALL_TAB_PRIVS 
WHERE GRANTEE = 'NV0008' AND PRIVILEGE = 'EXECUTE';
/

CREATE OR REPLACE VIEW USER_ROLE_PRIVS_VIEW AS
SELECT DISTINCT GRANTEE
FROM DBA_ROLE_PRIVS
WHERE GRANTED_ROLE = 'GIAOVU';


CREATE OR REPLACE PROCEDURE XOAKHMO
(
    MAHP CHAR,
    HK NUMBER,
    NAM NUMBER,
    MACT CHAR
)
AS
    STRSQL VARCHAR2(2000);
BEGIN
    STRSQL := 'DELETE FROM ADMIN.DANGKY WHERE MAHP = ''' || MAHP || ''' AND HK = ' || HK || ' AND NAM = ' || NAM || ' AND MACT LIKE ''%' || MACT || '%''';
    EXECUTE IMMEDIATE STRSQL;
    
    STRSQL := 'DELETE FROM ADMIN.PHANCONG WHERE MAHP = ''' || MAHP || ''' AND HK = ' || HK || ' AND NAM = ' || NAM || ' AND MACT LIKE ''%' || MACT || '%''';
    EXECUTE IMMEDIATE STRSQL;
    
    STRSQL := 'DELETE FROM ADMIN.KHMO WHERE MAHP = ''' || MAHP || ''' AND HK = ' || HK || ' AND NAM = ' || NAM || ' AND MACT LIKE ''%' || MACT || '%''';
    EXECUTE IMMEDIATE STRSQL;
END;
/

GRANT EXECUTE ON XOAKHMO TO GIAOVU;
/

CREATE OR REPLACE PROCEDURE THEMDONVI
(
    MAHP CHAR,
    HK NUMBER,
    NAM NUMBER,
    MACT CHAR
)
AS
    STRSQL VARCHAR2(2000);
BEGIN
    STRSQL := 'DELETE FROM ADMIN.DANGKY WHERE MAHP = ''' || MAHP || ''' AND HK = ' || HK || ' AND NAM = ' || NAM || ' AND MACT LIKE ''%' || MACT || '%''';
    EXECUTE IMMEDIATE STRSQL;
    
    STRSQL := 'DELETE FROM ADMIN.PHANCONG WHERE MAHP = ''' || MAHP || ''' AND HK = ' || HK || ' AND NAM = ' || NAM || ' AND MACT LIKE ''%' || MACT || '%''';
    EXECUTE IMMEDIATE STRSQL;
    
    STRSQL := 'DELETE FROM ADMIN.KHMO WHERE MAHP = ''' || MAHP || ''' AND HK = ' || HK || ' AND NAM = ' || NAM || ' AND MACT LIKE ''%' || MACT || '%''';
    EXECUTE IMMEDIATE STRSQL;
END;
/


CREATE OR REPLACE PROCEDURE SP_GetEmpID(
    empID OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN empID FOR
    SELECT ADMIN.NHANSU.MANV
    FROM ADMIN.NHANSU
    WHERE ADMIN.NHANSU.VAITRO NOT IN ('NHAN VIEN CO BAN','GIAO VU');
END SP_GetEmpID;
/
GRANT EXECUTE ON SP_GetEmpID TO TRUONGDONVI; 
GRANT EXECUTE ON SP_GetEmpID TO ROLE_TK;
GRANT EXECUTE ON SP_GetEmpID TO GIAOVU;
/

